### PR TITLE
Fix cgo errors for Go 1.15.

### LINKED ISSUE #245: No longer compiles after go 1.15 released
program stops compiling after 1.15 go release:

[sciter]$ go build
# github.com/sciter-sdk/go-sciter
../../../go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter.go:110:145: cannot use _cgo0 (type _Ctype_HWINDOW) as type unsafe.Pointer in argument to _Cfunc_SciterDataReady
../../../go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter.go:141:85: cannot use _cgo0 (type _Ctype_HWINDOW) as type unsafe.Pointer in argument to _Cfunc_SciterDataReadyAsync
../../../go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter.go:151:120: cannot use _cgo0 (type _Ctype_HWINDOW) as type unsafe.Pointer in argument to _Cfunc_SciterLoadFile
../../../go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter.go:174:104: cannot use _cgo0 (type _Ctype_HWINDOW) as type unsafe.Pointer in argument to _Cfunc_SciterLoadHtml
../../../go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter.go:242:142: cannot use _cgo0 (type _Ctype_HWINDOW) as type unsafe.Pointer in argument to _Cfunc_SciterSetCallback
../../../go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter.go:296:60: cannot use _cgo0 (type _Ctype_HWINDOW) as type unsafe.Pointer in argument to _Cfunc_SciterSetCSS
../../../go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter.go:319:110: cannot use _cgo0 (type _Ctype_HWINDOW) as type unsafe.Pointer in argument to _Cfunc_SciterSetMediaType
../../../go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter.go:330:96: cannot use _cgo0 (type _Ctype_HWINDOW) as type unsafe.Pointer in argument to _Cfunc_SciterGetMinWidth
../../../go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter.go:339:106: cannot use _cgo0 (type _Ctype_HWINDOW) as type unsafe.Pointer in argument to _Cfunc_SciterGetMinHeight
../../../go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter.go:359:48: cannot use _cgo0 (type _Ctype_HWINDOW) as type unsafe.Pointer in argument to _Cfunc_SciterCall
../../../go/pkg/mod/github.com/sciter-sdk/go-sciter@v0.5.0/sciter.go:359:48: too many errors

### PR DESCRIPTION
**Pull request by pravic**
closes #251
fixes #245

### CODE REVIEW

**Comment by pravic** [comment]
@shumatech @antichown  Could you try this?

**Comment by pravic** [comment]
Interesting. It fails on Windows.

**Comment by antichown** [comment]
go get -x github.com/sciter-sdk/go-sciter


 github.com/sciter-sdk/go-sciter
../../go/src/github.com/sciter-sdk/go-sciter/sciter.go:1052:142: cannot use _cgo1 (type *_Ctype_HWINDOW) as type **_Ctype_struct__GtkWidget in argument to _Cfunc_SciterGetElementHwnd


 does not work

**Comment by pkaftj** [comment]
> 去获取 -x github.com/sciter-sdk/go-sciter
> 
> github.com/sciter-sdk/go-sciter
> ../../go/src/github.com/sciter-sdk/go-sciter/sciter.go:1052:142: 不能使用 _cgo1 (type *_Ctype_HWINDOW) 是在 _Cfunc_SciterGetElementHwnd 的参数中输入 **_Ctype_struct__GtkWidget
> 
> 感应

Try this one ```https://github.com/pkaftj/sciter-go```

**Comment by pkaftj** [comment]
> go get -x github.com/sciter-sdk/go-sciter
> 
> github.com/sciter-sdk/go-sciter
> ../../go/src/github.com/sciter-sdk/go-sciter/sciter.go:1052:142: cannot use _cgo1 (type *_Ctype_HWINDOW) as type **_Ctype_struct__GtkWidget in argument to _Cfunc_SciterGetElementHwnd
> 
> does not work

Try this one ```https://github.com/pkaftj/sciter-go```

**Pull request closed without merging**
