### PR TITLE
add some demos of sciter usage for beginer

### PR DESCRIPTION
**Pull request by taonylu**
I added some demos for beginers. Comment inside is Chinese. But for English user, it's easily to understand.
Hope this will help someone. Thank you. Taony

### CODE REVIEW

**Comment by cjmxp** [comment]
@taonylu 提交的代码不能编译兄弟我用你的分支都编译不过就是你加的两个函数 go1.9

**Comment by taonylu** [comment]
removed functions. Only add demos.

**Comment by pravic** [comment]
>  Comment inside is Chinese. But for English user, it's easily to understand.

Seriosly? :) I don't think so. Can you translate comments in English, please?
Also it would be nice to add a short description for each demo.

**Comment by taonylu** [comment]
If a English user read codes, I am sure he will understand the meaning. For example, "delElement". The comment is just explain it in Chinese.  I know it will made English user  feel a little confused when they see those unknown characters. I wll make some translations for demos if there's no Englsih meaning.

**Pull request merged**
